from collections import namedtuple
from typing import Protocol

# (source, as_of): what a read result should be attributed to, e.g.
# Citation("local clinic records", "updated just now") today, or later
# Citation("ClinicEMR", "as of 2026-09-24 06:00 IST") once a real adapter exists.
Citation = namedtuple("Citation", ["source", "as_of"])


class ClinicalAdapter(Protocol):
    """Patient/visit/follow-up data -- what a real EMR would actually own."""

    def register_patient(self, conn, slots): ...
    def record_visit(self, conn, slots): ...
    def set_followup(self, conn, slots): ...
    def cancel_followup(self, conn, slots): ...
    def reschedule_followup(self, conn, slots): ...
    def nearest_pending_followup(self, conn, patient_id): ...
    def pending_followups_for_patient(self, conn, patient_id): ...
    def book_appointment(self, conn, slots): ...
    def cancel_appointment(self, conn, slots): ...
    def reschedule_appointment(self, conn, slots): ...
    def restore_appointment(self, conn, slots): ...
    def check_in(self, conn, slots): ...
    def start_consultation(self, conn, slots): ...
    def complete(self, conn, slots): ...
    def mark_no_show(self, conn, slots): ...
    def queue_for_date(self, conn, appt_date): ...
    def queue_entry(self, conn, appointment_id): ...
    def queue_options(self, conn, appt_date): ...
    def find_by_token(self, conn, appt_date, number): ...
    def next_to_call(self, conn, appt_date): ...
    def queue_snapshot(self, conn, appt_date): ...
    def available_slots(self, conn, appt_date): ...
    def upcoming_appointments_for_patient(self, conn, patient_id): ...
    def next_appointment_for_patient(self, conn, patient_id): ...
    def scheduled_appointments(self, conn, start_date, end_date=None): ...
    def appointments_named(self, conn, name, start_date=None, end_date=None): ...
    def resolve_patient(self, conn, query, top_n=3): ...
    def resolve_patient_by_phone(self, conn, wa_id): ...
    def missed_followups(self, conn, as_of=None): ...
    def patient_lookup(self, conn, patient_id): ...
    def citation(self): ...


class OpsAdapter(Protocol):
    """Staff/attendance/expenses -- what generic EMRs never cover, and what
    stays local even after a clinic adopts one."""

    def register_staff(self, conn, slots): ...
    def log_attendance(self, conn, slots): ...
    def log_expense(self, conn, slots): ...
    def resolve_staff(self, conn, query, top_n=3): ...
    def day_end_cashbook(self, conn, on_date=None): ...
    def attendance_register(self, conn, on_date=None): ...
    def citation(self): ...
